version: '3.4'

services:

  catelogdb:
    image: mongo

  catelog.api:
    image: ${DOCKER_REGISTRY-}catelogapi
    build:
      context: .
      dockerfile: Services/Catelog/Catelog.Api/Dockerfile
  
  # Mongo Express Service
  mongo-express:
    image: mongo-express:latest # latest image


volumes:
  mongo_data:


